prime:
  proper-name: Prime Video
  attribution: "By Pentagram Studio - https://amazon.com/, Public Domain, https://commons.wikimedia.org/w/index.php?curid=130197302"
netflix:
  proper-name: Netflix
  attribution: "By Netflix - https://www.netflix.com/, Public Domain, https://commons.wikimedia.org/w/index.php?curid=46541697"
paramount:
  proper-name: "Paramount+"
  attribution: "By Paramount Global - Loyalkaspar - https://www.paramountplus.com/, Public Domain, https://commons.wikimedia.org/w/index.php?curid=126589664"
apple:
  proper-name: "Apple TV+"
  attribution: "By Original logo by Apple Inc. - https://www.apple.com/tv/, Public Domain, https://commons.wikimedia.org/w/index.php?curid=77611029"
